name: publish

on:
  push:
    branches:
      - main
    paths:
      - '*/PKGBUILD'

jobs:
  find:
    runs-on: ubuntu-latest
    outputs:
      pkgs: ${{ steps.find.outputs.pkgs }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Find updated packages
        id: find
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          pkgs=$(git diff --name-only "${{ github.event.before }}" HEAD "*/.SRCINFO" \
            | xargs -n1 dirname | sort -u)
          echo "pkgs=$(echo "$pkgs" | jq -R -s -c 'split("\n") | map(select(. != ""))')" >> "$GITHUB_OUTPUT"
          echo "Found packages: $pkgs"

  publish:
    needs: find
    if: ${{ needs.find.outputs.pkgs != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: ${{ fromJson(needs.find.outputs.pkgs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Publish package
        uses: KSXGitHub/github-actions-deploy-aur@084b0d9b15415bf9cdb65d44dad1efe37a354050 # v4.2.0
        with:
          pkgname: ${{ matrix.pkg }}
          pkgbuild: ${{ matrix.pkg }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
